---
title: "Mali - Variables harmonization for all surveys and years"
author: "Giovanni GADO"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


```{r packages needed}
library(haven)
library(labelled)
library(tidyverse)
library(dplyr)
library(Hmisc)
library(gtsummary)
library(readxl)
library(foreign)
```



```{r}
rm(list = ls())
```

```{r environment settings}

dir_input_data = "C:/Users/ASUS/Desktop/ISEP 3/Statistique exploratoire spatiale/Projet_1/Data/input_data"
dir_output_data = "C:/Users/ASUS/Desktop/ISEP 3/Statistique exploratoire spatiale/Projet_1/Data/output_data"
```

```{r read harmonization excel file}

Mali_Harmonization_variables <- read_excel(paste0(dir_input_data,"/MLI_Harmonization.xlsx"), 
    sheet = "variables_harmonization")
#View(Mali_Harmonization_variables)

Mali_Harmonization_description <- read_excel(paste0(dir_input_data,"/MLI_Harmonization.xlsx"), 
    sheet = "description")
#View(Mali_Harmonization_description)
```

```{r data importation}

lst_data = Mali_Harmonization_description$Data
lst_test = Mali_Harmonization_description$Name
lst_data
lst_test

for(i in 1:length(lst_data)) {
  if (is.na(lst_data[i])){
    print(paste0("Le fichier ",lst_test[i], " n'existe pas"))}
  else {
    assign(lst_test[i],
         read_sav(paste0(dir_input_data,"/",lst_data[i])))}
  }

```





```{r select and rename columns needed}

for (j in 1:length(lst_test)){
  if (exists(lst_test[j])) {
         df=  get(lst_test[j], envir = .GlobalEnv)
         print(lst_test[j])
          for (i in 1:nrow(Mali_Harmonization_variables)){
            df[,Mali_Harmonization_variables$NewVariable_Name[i]]=ifelse(is.na(Mali_Harmonization_variables[i,lst_test[j]]),NA,df[,Mali_Harmonization_variables[i,lst_test[j]][[1]]])
          }
    df<-df %>% select(Mali_Harmonization_variables$NewVariable_Name)
    write_sav(df, paste0(dir_output_data,"/",lst_test[j],".sav"))
    
}}



```




